sudo: required
services:
  - docker

before_install:
  - docker build -t danielvnanok:tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielvnanok:tests npm test -- --coverage

after_success:
  - docker build -t danielvnanok/client ./client 
  - docker build -t danielvnanok/nginx ./nginx
  - docker build -t danielvnanok/api ./server
  - docker build -t danielvnanok/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push danielvnanok/client
  - docker push danielvnanok/nginx
  - docker push danielvnanok/api
  - docker push danielvnanok/worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-894244321548
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY